# Generated by Django 4.2.3 on 2024-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0002_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='serialNumber',
            new_name='audit',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='onsite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
