# Generated by Django 4.2.3 on 2024-04-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0003_rename_serialnumber_item_audit_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dateOut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dateReturn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
