# Generated by Django 4.2.3 on 2024-04-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0007_itemtype_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
