# Generated by Django 4.2.3 on 2024-04-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0009_item_cpu_item_gpu_item_ram_item_deviceserialnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
