# Generated by Django 4.2.3 on 2024-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0010_remove_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='audit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
