# Generated by Django 4.2.3 on 2024-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0016_itemtype_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
