# Generated by Django 4.2.3 on 2024-04-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0022_alter_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtypes',
            name='user',
        ),
    ]
