# Generated by Django 4.2.3 on 2024-04-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0027_alter_item_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemTypes',
            new_name='ItemType',
        ),
    ]
