# Generated by Django 4.2.3 on 2024-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0033_remove_itemtype_user_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
