# Generated by Django 4.2.3 on 2024-04-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0035_remove_item_is_booked_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
