# Generated by Django 4.2.3 on 2024-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0037_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warranty_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
