# Generated by Django 4.2.3 on 2024-04-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolSystem', '0038_item_warranty_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
